export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS';
export const GET_PROJECTS_ERROR = 'GET_PROJECTS_ERROR';

export const ASSIGN_CURRENT_PROJECT = 'ASSIGN_CURRENT_PROJECT';

export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS';
export const ADD_PROJECT_ERROR = 'ADD_PROJECT_ERROR';

export const UPDATE_PROJECT_TASKS = 'UPDATE_PROJECT_TASKS';
export const UPDATE_PROJECT_TASKS_ERROR = 'UPDATE_PROJECT_TASKS_ERROR';

export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_ERROR = 'DELETE_PROJECT_ERROR';

export const PROJECT_LOADING = 'PROJECT_LOADING';
export const RESET_PROJECT_STATE = 'RESET_PROJECT_STATE';
